services:
  localstack:
    image: localstack/localstack:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: sqs
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
