[package]
name = "proto"
edition.workspace = true
version.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
prost-build.workspace = true
